{
 "title": "Transaction",
 "time": { "from": "2009-12-26T16:10:10.350Z", "to": "2010-03-07T17:11:23.513Z" },
 "refresh": "5s",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "options": {
    "content": "### Suspicious Transaction Criteria\n\nA transaction is flagged as **suspicious** as of now is based on the following rules:\n\n- Negative amount charged\n\n"
   }
  },
  {
   "title": "Top 5 Suspicious Transaction by Merchant Location",
   "type": "table",
   "gridPos": { "h": 7, "w": 7, "x": 6, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \r\n    merchant_city as \"Merchant City\", \r\n    merchant_state as \"Merchant State\", \r\n    COUNT(*) AS \"Suspicious transaction count\"\r\nFROM \r\n    transaction\r\nWHERE \r\n    is_suspicious = TRUE\r\nGROUP BY \r\n    merchant_city, \r\n    merchant_state\r\nORDER BY \r\n    \"Suspicious transaction count\" DESC\r\nLIMIT 5;\r\n"
    }
   ]
  },
  {
   "title": "Transaction amount distribution",
   "type": "histogram",
   "gridPos": { "h": 17, "w": 7, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "SELECT amount\r\n FROM transaction \r\n GROUP BY amount\r\n ;"
    }
   ]
  },
  {
   "type": "piechart",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(id) as \"Total number of transaction\"FROM transaction;"
    },
    {
     "rawSql": "SELECT COUNT(is_suspicious) as \"Suspicious transaction flagged\"\r\nFROM transaction \r\nWHERE is_suspicious=true;"
    }
   ]
  },
  {
   "title": "Amount of Transaction over time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 6, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT date as Time, \r\namount as \"Total amount\"\r\nFROM transaction \r\nWHERE is_suspicious=False"
    }
   ]
  },
  {
   "title": "Suspicious vs Normal Transaction over time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 18 },
   "targets": [
    {
     "rawSql": "SELECT \r\n    date_trunc('hour', date) AS time,\r\n    SUM(CASE WHEN is_suspicious THEN 1 ELSE 0 END) OVER (ORDER BY date_trunc('hour', date)) AS \"Suspicious transaction\",\r\n    SUM(CASE WHEN NOT is_suspicious THEN 1 ELSE 0 END) OVER (ORDER BY date_trunc('hour', date)) AS \"Normal transaction\"\r\nFROM \r\n    transaction\r\nORDER BY \r\n    time;\r\n"
    }
   ]
  }
 ]
}